### ISSUE TITLE
Suggestion: use the keys ASDFG instead of ABCDE

### ISSUE THREAD

**Issue by Filip013** [CyberShadow/DuolingoMoreKeys#1]
Hi, CyberShadow, I really like your script. I use it mainly on the new Chinese course and I think its awesome! However, I have one suggestion for you.

I like the fact that you prepared for the situation where there are more than ten options in the word bank by using the characters ABCDE, etc. So far I only had to use the letters up to C. However, it might be easier if the letters needed were side by side, such as QWERTY or ASDFG. Perhaps using the second row is better because the little hooks on the F key.

I've never done any changes to scripts before, but I tried it now and it worked for me, but some people might not think of it.

Again, awesome job! Thanks!

**Comment by CyberShadow** [comment]
That's a decent idea. I've already thought about it, however it won't work for me as I use Dvorak and not QWERTY, so ASDFG would be AOEUI for me. There are also more common layouts like AZERTY where this would be an issue too.

Ideally this would be an option, however I looked into adding an options page to extensions, and it looked like doing it in away that works on all browsers wasn't trivial...

In the end what I went with was put the list of keys front and center in the script, so that it's easy to edit once you install it.

**Comment by Filip013** [comment]
Thanks, for replying!

Hmm... Yeah, I guess you’re right. My own keyboard is QWERTZ, so I can see the problem here. I will close this issue then.

Anyway, I’m glad to see that you’re so quick to answer. With all the changes that Duolingo is doing, I’m glad that this script might just stay up to date. Cheers!

**Comment by CyberShadow** [comment]
OK, I had an idea for a better compromise. Can you give this a go?

https://github.com/CyberShadow/DuolingoMoreKeys#configuration

**Comment by Filip013** [comment]
Oh, yeah! That works great and lets people know they can make changes. Awesome! Thanks!
